name = "PMSimulator"
uuid = "e1cec47b-adf4-44e7-b68f-a49faa66b4f0"
authors = ["Acme Corp"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
